### ISSUE TITLE
The whole pip thing isn't working for me

### ISSUE THREAD

**Issue by graemetlloyd** [macrojc/macrojc#5]
First I got:

Graemes-MacBook-Pro-2:~ gral$ pip
-bash: pip: command not found
Graemes-MacBook-Pro-2:~ gral$ sudo pip
Password:
sudo: pip: command not found

Then I installed Python and tried:

python get-pip.py

But get:

Collecting pip
  Using cached pip-6.0.8-py2.py3-none-any.whl
Installing collected packages: pip

  Exception:
  Traceback (most recent call last):
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/req/req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/req/req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/var/folders/03/nj9nr1k96h51w6cl57h14jtm0fp56q/T/tmpRpTbFB/pip.zip/pip/wheel.py", line 205, in clobber
      os.makedirs(destdir)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip'

Which means nothing to me!

K, thx.

**Comment by wrightaprilm** [comment]
What does the output look like if you do sudo python get-pip.py?

**Comment by graemetlloyd** [comment]
The directory '/Users/gral/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/gral/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/gral/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting pip
  Downloading pip-6.0.8-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 344kB/s 
Installing collected packages: pip

Successfully installed pip-6.0.8

**Comment by graemetlloyd** [comment]
Hurrah?

**Comment by graemetlloyd** [comment]
https://www.youtube.com/watch?v=r0qBaBb1Y-U

**Comment by wrightaprilm** [comment]
So, it looks like it works, but there might be some permissions issues (maybe your user account isn't the master?), but should be OK.

**Comment by graemetlloyd** [comment]
Yep. Thanks April!
